parameters:
  # Class responsible to inject service container instance in all contexts.
  drupal.behat.context_initializer.service_container.class: Europa\Drupal\DrupalExtension\Context\Initializer\ServiceContainerInitializer

services:
  drupal.behat.context_initializer.service_container:
    class: %drupal.behat.context_initializer.service_container.class%
    arguments:
      - "@service_container"
    tags:
      -  { name: context.initializer }
